// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/admission.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Admission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	Course        string                 `protobuf:"bytes,3,opt,name=course,proto3" json:"course,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AppliedDate   string                 `protobuf:"bytes,5,opt,name=applied_date,json=appliedDate,proto3" json:"applied_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Admission) Reset() {
	*x = Admission{}
	mi := &file_proto_admission_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Admission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admission) ProtoMessage() {}

func (x *Admission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admission_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admission.ProtoReflect.Descriptor instead.
func (*Admission) Descriptor() ([]byte, []int) {
	return file_proto_admission_proto_rawDescGZIP(), []int{0}
}

func (x *Admission) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Admission) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *Admission) GetCourse() string {
	if x != nil {
		return x.Course
	}
	return ""
}

func (x *Admission) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Admission) GetAppliedDate() string {
	if x != nil {
		return x.AppliedDate
	}
	return ""
}

type ApplyAdmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentName   string                 `protobuf:"bytes,1,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	Course        string                 `protobuf:"bytes,2,opt,name=course,proto3" json:"course,omitempty"`
	AppliedDate   string                 `protobuf:"bytes,3,opt,name=applied_date,json=appliedDate,proto3" json:"applied_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyAdmissionRequest) Reset() {
	*x = ApplyAdmissionRequest{}
	mi := &file_proto_admission_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyAdmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyAdmissionRequest) ProtoMessage() {}

func (x *ApplyAdmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admission_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyAdmissionRequest.ProtoReflect.Descriptor instead.
func (*ApplyAdmissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_admission_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyAdmissionRequest) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *ApplyAdmissionRequest) GetCourse() string {
	if x != nil {
		return x.Course
	}
	return ""
}

func (x *ApplyAdmissionRequest) GetAppliedDate() string {
	if x != nil {
		return x.AppliedDate
	}
	return ""
}

type GetAdmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdmissionRequest) Reset() {
	*x = GetAdmissionRequest{}
	mi := &file_proto_admission_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdmissionRequest) ProtoMessage() {}

func (x *GetAdmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admission_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdmissionRequest.ProtoReflect.Descriptor instead.
func (*GetAdmissionRequest) Descriptor() ([]byte, []int) {
	return file_proto_admission_proto_rawDescGZIP(), []int{2}
}

func (x *GetAdmissionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AdmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admission     *Admission             `protobuf:"bytes,1,opt,name=admission,proto3" json:"admission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdmissionResponse) Reset() {
	*x = AdmissionResponse{}
	mi := &file_proto_admission_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdmissionResponse) ProtoMessage() {}

func (x *AdmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admission_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdmissionResponse.ProtoReflect.Descriptor instead.
func (*AdmissionResponse) Descriptor() ([]byte, []int) {
	return file_proto_admission_proto_rawDescGZIP(), []int{3}
}

func (x *AdmissionResponse) GetAdmission() *Admission {
	if x != nil {
		return x.Admission
	}
	return nil
}

type ListAdmissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdmissionsRequest) Reset() {
	*x = ListAdmissionsRequest{}
	mi := &file_proto_admission_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdmissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdmissionsRequest) ProtoMessage() {}

func (x *ListAdmissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admission_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdmissionsRequest.ProtoReflect.Descriptor instead.
func (*ListAdmissionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_admission_proto_rawDescGZIP(), []int{4}
}

type ListAdmissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admissions    []*Admission           `protobuf:"bytes,1,rep,name=admissions,proto3" json:"admissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAdmissionsResponse) Reset() {
	*x = ListAdmissionsResponse{}
	mi := &file_proto_admission_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAdmissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAdmissionsResponse) ProtoMessage() {}

func (x *ListAdmissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admission_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAdmissionsResponse.ProtoReflect.Descriptor instead.
func (*ListAdmissionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_admission_proto_rawDescGZIP(), []int{5}
}

func (x *ListAdmissionsResponse) GetAdmissions() []*Admission {
	if x != nil {
		return x.Admissions
	}
	return nil
}

var File_proto_admission_proto protoreflect.FileDescriptor

const file_proto_admission_proto_rawDesc = "" +
	"\n" +
	"\x15proto/admission.proto\x12\tadmission\"\x91\x01\n" +
	"\tAdmission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12\x16\n" +
	"\x06course\x18\x03 \x01(\tR\x06course\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\fapplied_date\x18\x05 \x01(\tR\vappliedDate\"u\n" +
	"\x15ApplyAdmissionRequest\x12!\n" +
	"\fstudent_name\x18\x01 \x01(\tR\vstudentName\x12\x16\n" +
	"\x06course\x18\x02 \x01(\tR\x06course\x12!\n" +
	"\fapplied_date\x18\x03 \x01(\tR\vappliedDate\"%\n" +
	"\x13GetAdmissionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"G\n" +
	"\x11AdmissionResponse\x122\n" +
	"\tadmission\x18\x01 \x01(\v2\x14.admission.AdmissionR\tadmission\"\x17\n" +
	"\x15ListAdmissionsRequest\"N\n" +
	"\x16ListAdmissionsResponse\x124\n" +
	"\n" +
	"admissions\x18\x01 \x03(\v2\x14.admission.AdmissionR\n" +
	"admissions2\x89\x02\n" +
	"\x10AdmissionService\x12P\n" +
	"\x0eApplyAdmission\x12 .admission.ApplyAdmissionRequest\x1a\x1c.admission.AdmissionResponse\x12L\n" +
	"\fGetAdmission\x12\x1e.admission.GetAdmissionRequest\x1a\x1c.admission.AdmissionResponse\x12U\n" +
	"\x0eListAdmissions\x12 .admission.ListAdmissionsRequest\x1a!.admission.ListAdmissionsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_admission_proto_rawDescOnce sync.Once
	file_proto_admission_proto_rawDescData []byte
)

func file_proto_admission_proto_rawDescGZIP() []byte {
	file_proto_admission_proto_rawDescOnce.Do(func() {
		file_proto_admission_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admission_proto_rawDesc), len(file_proto_admission_proto_rawDesc)))
	})
	return file_proto_admission_proto_rawDescData
}

var file_proto_admission_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_admission_proto_goTypes = []any{
	(*Admission)(nil),              // 0: admission.Admission
	(*ApplyAdmissionRequest)(nil),  // 1: admission.ApplyAdmissionRequest
	(*GetAdmissionRequest)(nil),    // 2: admission.GetAdmissionRequest
	(*AdmissionResponse)(nil),      // 3: admission.AdmissionResponse
	(*ListAdmissionsRequest)(nil),  // 4: admission.ListAdmissionsRequest
	(*ListAdmissionsResponse)(nil), // 5: admission.ListAdmissionsResponse
}
var file_proto_admission_proto_depIdxs = []int32{
	0, // 0: admission.AdmissionResponse.admission:type_name -> admission.Admission
	0, // 1: admission.ListAdmissionsResponse.admissions:type_name -> admission.Admission
	1, // 2: admission.AdmissionService.ApplyAdmission:input_type -> admission.ApplyAdmissionRequest
	2, // 3: admission.AdmissionService.GetAdmission:input_type -> admission.GetAdmissionRequest
	4, // 4: admission.AdmissionService.ListAdmissions:input_type -> admission.ListAdmissionsRequest
	3, // 5: admission.AdmissionService.ApplyAdmission:output_type -> admission.AdmissionResponse
	3, // 6: admission.AdmissionService.GetAdmission:output_type -> admission.AdmissionResponse
	5, // 7: admission.AdmissionService.ListAdmissions:output_type -> admission.ListAdmissionsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_admission_proto_init() }
func file_proto_admission_proto_init() {
	if File_proto_admission_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admission_proto_rawDesc), len(file_proto_admission_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admission_proto_goTypes,
		DependencyIndexes: file_proto_admission_proto_depIdxs,
		MessageInfos:      file_proto_admission_proto_msgTypes,
	}.Build()
	File_proto_admission_proto = out.File
	file_proto_admission_proto_goTypes = nil
	file_proto_admission_proto_depIdxs = nil
}
