// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/hr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Employee struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Department    string                 `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Doj           string                 `protobuf:"bytes,5,opt,name=doj,proto3" json:"doj,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Employee) Reset() {
	*x = Employee{}
	mi := &file_proto_hr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Employee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Employee) ProtoMessage() {}

func (x *Employee) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Employee.ProtoReflect.Descriptor instead.
func (*Employee) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{0}
}

func (x *Employee) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Employee) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Employee) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Employee) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Employee) GetDoj() string {
	if x != nil {
		return x.Doj
	}
	return ""
}

type AddEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Department    string                 `protobuf:"bytes,2,opt,name=department,proto3" json:"department,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Doj           string                 `protobuf:"bytes,4,opt,name=doj,proto3" json:"doj,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEmployeeRequest) Reset() {
	*x = AddEmployeeRequest{}
	mi := &file_proto_hr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEmployeeRequest) ProtoMessage() {}

func (x *AddEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEmployeeRequest.ProtoReflect.Descriptor instead.
func (*AddEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{1}
}

func (x *AddEmployeeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddEmployeeRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *AddEmployeeRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AddEmployeeRequest) GetDoj() string {
	if x != nil {
		return x.Doj
	}
	return ""
}

type GetEmployeeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEmployeeRequest) Reset() {
	*x = GetEmployeeRequest{}
	mi := &file_proto_hr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEmployeeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEmployeeRequest) ProtoMessage() {}

func (x *GetEmployeeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEmployeeRequest.ProtoReflect.Descriptor instead.
func (*GetEmployeeRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{2}
}

func (x *GetEmployeeRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmployeeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employee      *Employee              `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmployeeResponse) Reset() {
	*x = EmployeeResponse{}
	mi := &file_proto_hr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmployeeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmployeeResponse) ProtoMessage() {}

func (x *EmployeeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmployeeResponse.ProtoReflect.Descriptor instead.
func (*EmployeeResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{3}
}

func (x *EmployeeResponse) GetEmployee() *Employee {
	if x != nil {
		return x.Employee
	}
	return nil
}

type ListEmployeesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmployeesRequest) Reset() {
	*x = ListEmployeesRequest{}
	mi := &file_proto_hr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmployeesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmployeesRequest) ProtoMessage() {}

func (x *ListEmployeesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmployeesRequest.ProtoReflect.Descriptor instead.
func (*ListEmployeesRequest) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{4}
}

type ListEmployeesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Employees     []*Employee            `protobuf:"bytes,1,rep,name=employees,proto3" json:"employees,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEmployeesResponse) Reset() {
	*x = ListEmployeesResponse{}
	mi := &file_proto_hr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEmployeesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEmployeesResponse) ProtoMessage() {}

func (x *ListEmployeesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEmployeesResponse.ProtoReflect.Descriptor instead.
func (*ListEmployeesResponse) Descriptor() ([]byte, []int) {
	return file_proto_hr_proto_rawDescGZIP(), []int{5}
}

func (x *ListEmployeesResponse) GetEmployees() []*Employee {
	if x != nil {
		return x.Employees
	}
	return nil
}

var File_proto_hr_proto protoreflect.FileDescriptor

const file_proto_hr_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/hr.proto\x12\x02hr\"t\n" +
	"\bEmployee\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"department\x18\x03 \x01(\tR\n" +
	"department\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x10\n" +
	"\x03doj\x18\x05 \x01(\tR\x03doj\"n\n" +
	"\x12AddEmployeeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"department\x18\x02 \x01(\tR\n" +
	"department\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x10\n" +
	"\x03doj\x18\x04 \x01(\tR\x03doj\"$\n" +
	"\x12GetEmployeeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"<\n" +
	"\x10EmployeeResponse\x12(\n" +
	"\bemployee\x18\x01 \x01(\v2\f.hr.EmployeeR\bemployee\"\x16\n" +
	"\x14ListEmployeesRequest\"C\n" +
	"\x15ListEmployeesResponse\x12*\n" +
	"\temployees\x18\x01 \x03(\v2\f.hr.EmployeeR\temployees2\xcb\x01\n" +
	"\tHRService\x12;\n" +
	"\vAddEmployee\x12\x16.hr.AddEmployeeRequest\x1a\x14.hr.EmployeeResponse\x12;\n" +
	"\vGetEmployee\x12\x16.hr.GetEmployeeRequest\x1a\x14.hr.EmployeeResponse\x12D\n" +
	"\rListEmployees\x12\x18.hr.ListEmployeesRequest\x1a\x19.hr.ListEmployeesResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_hr_proto_rawDescOnce sync.Once
	file_proto_hr_proto_rawDescData []byte
)

func file_proto_hr_proto_rawDescGZIP() []byte {
	file_proto_hr_proto_rawDescOnce.Do(func() {
		file_proto_hr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hr_proto_rawDesc), len(file_proto_hr_proto_rawDesc)))
	})
	return file_proto_hr_proto_rawDescData
}

var file_proto_hr_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_hr_proto_goTypes = []any{
	(*Employee)(nil),              // 0: hr.Employee
	(*AddEmployeeRequest)(nil),    // 1: hr.AddEmployeeRequest
	(*GetEmployeeRequest)(nil),    // 2: hr.GetEmployeeRequest
	(*EmployeeResponse)(nil),      // 3: hr.EmployeeResponse
	(*ListEmployeesRequest)(nil),  // 4: hr.ListEmployeesRequest
	(*ListEmployeesResponse)(nil), // 5: hr.ListEmployeesResponse
}
var file_proto_hr_proto_depIdxs = []int32{
	0, // 0: hr.EmployeeResponse.employee:type_name -> hr.Employee
	0, // 1: hr.ListEmployeesResponse.employees:type_name -> hr.Employee
	1, // 2: hr.HRService.AddEmployee:input_type -> hr.AddEmployeeRequest
	2, // 3: hr.HRService.GetEmployee:input_type -> hr.GetEmployeeRequest
	4, // 4: hr.HRService.ListEmployees:input_type -> hr.ListEmployeesRequest
	3, // 5: hr.HRService.AddEmployee:output_type -> hr.EmployeeResponse
	3, // 6: hr.HRService.GetEmployee:output_type -> hr.EmployeeResponse
	5, // 7: hr.HRService.ListEmployees:output_type -> hr.ListEmployeesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_hr_proto_init() }
func file_proto_hr_proto_init() {
	if File_proto_hr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hr_proto_rawDesc), len(file_proto_hr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hr_proto_goTypes,
		DependencyIndexes: file_proto_hr_proto_depIdxs,
		MessageInfos:      file_proto_hr_proto_msgTypes,
	}.Build()
	File_proto_hr_proto = out.File
	file_proto_hr_proto_goTypes = nil
	file_proto_hr_proto_depIdxs = nil
}
