// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/attendance.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Attendance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     int32                  `protobuf:"varint,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // Present / Absent / Leave
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attendance) Reset() {
	*x = Attendance{}
	mi := &file_proto_attendance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attendance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attendance) ProtoMessage() {}

func (x *Attendance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attendance.ProtoReflect.Descriptor instead.
func (*Attendance) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{0}
}

func (x *Attendance) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Attendance) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *Attendance) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Attendance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MarkAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int32                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAttendanceRequest) Reset() {
	*x = MarkAttendanceRequest{}
	mi := &file_proto_attendance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAttendanceRequest) ProtoMessage() {}

func (x *MarkAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAttendanceRequest.ProtoReflect.Descriptor instead.
func (*MarkAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{1}
}

func (x *MarkAttendanceRequest) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

func (x *MarkAttendanceRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *MarkAttendanceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttendanceRequest) Reset() {
	*x = GetAttendanceRequest{}
	mi := &file_proto_attendance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttendanceRequest) ProtoMessage() {}

func (x *GetAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttendanceRequest.ProtoReflect.Descriptor instead.
func (*GetAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{2}
}

func (x *GetAttendanceRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type AttendanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attendance    *Attendance            `protobuf:"bytes,1,opt,name=attendance,proto3" json:"attendance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttendanceResponse) Reset() {
	*x = AttendanceResponse{}
	mi := &file_proto_attendance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttendanceResponse) ProtoMessage() {}

func (x *AttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttendanceResponse.ProtoReflect.Descriptor instead.
func (*AttendanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{3}
}

func (x *AttendanceResponse) GetAttendance() *Attendance {
	if x != nil {
		return x.Attendance
	}
	return nil
}

type ListAttendanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     int32                  `protobuf:"varint,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttendanceRequest) Reset() {
	*x = ListAttendanceRequest{}
	mi := &file_proto_attendance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttendanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttendanceRequest) ProtoMessage() {}

func (x *ListAttendanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttendanceRequest.ProtoReflect.Descriptor instead.
func (*ListAttendanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{4}
}

func (x *ListAttendanceRequest) GetStudentId() int32 {
	if x != nil {
		return x.StudentId
	}
	return 0
}

type ListAttendanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Attendance          `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttendanceResponse) Reset() {
	*x = ListAttendanceResponse{}
	mi := &file_proto_attendance_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttendanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttendanceResponse) ProtoMessage() {}

func (x *ListAttendanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_attendance_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttendanceResponse.ProtoReflect.Descriptor instead.
func (*ListAttendanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_attendance_proto_rawDescGZIP(), []int{5}
}

func (x *ListAttendanceResponse) GetRecords() []*Attendance {
	if x != nil {
		return x.Records
	}
	return nil
}

var File_proto_attendance_proto protoreflect.FileDescriptor

const file_proto_attendance_proto_rawDesc = "" +
	"\n" +
	"\x16proto/attendance.proto\x12\n" +
	"attendance\"g\n" +
	"\n" +
	"Attendance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\x05R\tstudentId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"b\n" +
	"\x15MarkAttendanceRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x05R\tstudentId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"&\n" +
	"\x14GetAttendanceRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"L\n" +
	"\x12AttendanceResponse\x126\n" +
	"\n" +
	"attendance\x18\x01 \x01(\v2\x16.attendance.AttendanceR\n" +
	"attendance\"6\n" +
	"\x15ListAttendanceRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\x05R\tstudentId\"J\n" +
	"\x16ListAttendanceResponse\x120\n" +
	"\arecords\x18\x01 \x03(\v2\x16.attendance.AttendanceR\arecords2\x94\x02\n" +
	"\x11AttendanceService\x12S\n" +
	"\x0eMarkAttendance\x12!.attendance.MarkAttendanceRequest\x1a\x1e.attendance.AttendanceResponse\x12Q\n" +
	"\rGetAttendance\x12 .attendance.GetAttendanceRequest\x1a\x1e.attendance.AttendanceResponse\x12W\n" +
	"\x0eListAttendance\x12!.attendance.ListAttendanceRequest\x1a\".attendance.ListAttendanceResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_attendance_proto_rawDescOnce sync.Once
	file_proto_attendance_proto_rawDescData []byte
)

func file_proto_attendance_proto_rawDescGZIP() []byte {
	file_proto_attendance_proto_rawDescOnce.Do(func() {
		file_proto_attendance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_attendance_proto_rawDesc), len(file_proto_attendance_proto_rawDesc)))
	})
	return file_proto_attendance_proto_rawDescData
}

var file_proto_attendance_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_attendance_proto_goTypes = []any{
	(*Attendance)(nil),             // 0: attendance.Attendance
	(*MarkAttendanceRequest)(nil),  // 1: attendance.MarkAttendanceRequest
	(*GetAttendanceRequest)(nil),   // 2: attendance.GetAttendanceRequest
	(*AttendanceResponse)(nil),     // 3: attendance.AttendanceResponse
	(*ListAttendanceRequest)(nil),  // 4: attendance.ListAttendanceRequest
	(*ListAttendanceResponse)(nil), // 5: attendance.ListAttendanceResponse
}
var file_proto_attendance_proto_depIdxs = []int32{
	0, // 0: attendance.AttendanceResponse.attendance:type_name -> attendance.Attendance
	0, // 1: attendance.ListAttendanceResponse.records:type_name -> attendance.Attendance
	1, // 2: attendance.AttendanceService.MarkAttendance:input_type -> attendance.MarkAttendanceRequest
	2, // 3: attendance.AttendanceService.GetAttendance:input_type -> attendance.GetAttendanceRequest
	4, // 4: attendance.AttendanceService.ListAttendance:input_type -> attendance.ListAttendanceRequest
	3, // 5: attendance.AttendanceService.MarkAttendance:output_type -> attendance.AttendanceResponse
	3, // 6: attendance.AttendanceService.GetAttendance:output_type -> attendance.AttendanceResponse
	5, // 7: attendance.AttendanceService.ListAttendance:output_type -> attendance.ListAttendanceResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_attendance_proto_init() }
func file_proto_attendance_proto_init() {
	if File_proto_attendance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_attendance_proto_rawDesc), len(file_proto_attendance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_attendance_proto_goTypes,
		DependencyIndexes: file_proto_attendance_proto_depIdxs,
		MessageInfos:      file_proto_attendance_proto_msgTypes,
	}.Build()
	File_proto_attendance_proto = out.File
	file_proto_attendance_proto_goTypes = nil
	file_proto_attendance_proto_depIdxs = nil
}
