// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/faculty.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Faculty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Department    string                 `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	Designation   string                 `protobuf:"bytes,5,opt,name=designation,proto3" json:"designation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Faculty) Reset() {
	*x = Faculty{}
	mi := &file_proto_faculty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Faculty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Faculty) ProtoMessage() {}

func (x *Faculty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_faculty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Faculty.ProtoReflect.Descriptor instead.
func (*Faculty) Descriptor() ([]byte, []int) {
	return file_proto_faculty_proto_rawDescGZIP(), []int{0}
}

func (x *Faculty) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Faculty) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Faculty) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Faculty) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Faculty) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

type CreateFacultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Department    string                 `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	Designation   string                 `protobuf:"bytes,4,opt,name=designation,proto3" json:"designation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFacultyRequest) Reset() {
	*x = CreateFacultyRequest{}
	mi := &file_proto_faculty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFacultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFacultyRequest) ProtoMessage() {}

func (x *CreateFacultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_faculty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFacultyRequest.ProtoReflect.Descriptor instead.
func (*CreateFacultyRequest) Descriptor() ([]byte, []int) {
	return file_proto_faculty_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFacultyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFacultyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateFacultyRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CreateFacultyRequest) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

type GetFacultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFacultyRequest) Reset() {
	*x = GetFacultyRequest{}
	mi := &file_proto_faculty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFacultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFacultyRequest) ProtoMessage() {}

func (x *GetFacultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_faculty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFacultyRequest.ProtoReflect.Descriptor instead.
func (*GetFacultyRequest) Descriptor() ([]byte, []int) {
	return file_proto_faculty_proto_rawDescGZIP(), []int{2}
}

func (x *GetFacultyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateFacultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Department    string                 `protobuf:"bytes,4,opt,name=department,proto3" json:"department,omitempty"`
	Designation   string                 `protobuf:"bytes,5,opt,name=designation,proto3" json:"designation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFacultyRequest) Reset() {
	*x = UpdateFacultyRequest{}
	mi := &file_proto_faculty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFacultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFacultyRequest) ProtoMessage() {}

func (x *UpdateFacultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_faculty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFacultyRequest.ProtoReflect.Descriptor instead.
func (*UpdateFacultyRequest) Descriptor() ([]byte, []int) {
	return file_proto_faculty_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFacultyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFacultyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFacultyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateFacultyRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *UpdateFacultyRequest) GetDesignation() string {
	if x != nil {
		return x.Designation
	}
	return ""
}

type DeleteFacultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFacultyRequest) Reset() {
	*x = DeleteFacultyRequest{}
	mi := &file_proto_faculty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFacultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFacultyRequest) ProtoMessage() {}

func (x *DeleteFacultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_faculty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFacultyRequest.ProtoReflect.Descriptor instead.
func (*DeleteFacultyRequest) Descriptor() ([]byte, []int) {
	return file_proto_faculty_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFacultyRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFacultyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFacultyResponse) Reset() {
	*x = DeleteFacultyResponse{}
	mi := &file_proto_faculty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFacultyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFacultyResponse) ProtoMessage() {}

func (x *DeleteFacultyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_faculty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFacultyResponse.ProtoReflect.Descriptor instead.
func (*DeleteFacultyResponse) Descriptor() ([]byte, []int) {
	return file_proto_faculty_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFacultyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FacultyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faculty       *Faculty               `protobuf:"bytes,1,opt,name=faculty,proto3" json:"faculty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FacultyResponse) Reset() {
	*x = FacultyResponse{}
	mi := &file_proto_faculty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FacultyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FacultyResponse) ProtoMessage() {}

func (x *FacultyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_faculty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FacultyResponse.ProtoReflect.Descriptor instead.
func (*FacultyResponse) Descriptor() ([]byte, []int) {
	return file_proto_faculty_proto_rawDescGZIP(), []int{6}
}

func (x *FacultyResponse) GetFaculty() *Faculty {
	if x != nil {
		return x.Faculty
	}
	return nil
}

type ListFacultiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFacultiesRequest) Reset() {
	*x = ListFacultiesRequest{}
	mi := &file_proto_faculty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFacultiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFacultiesRequest) ProtoMessage() {}

func (x *ListFacultiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_faculty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFacultiesRequest.ProtoReflect.Descriptor instead.
func (*ListFacultiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_faculty_proto_rawDescGZIP(), []int{7}
}

type ListFacultiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Faculties     []*Faculty             `protobuf:"bytes,1,rep,name=faculties,proto3" json:"faculties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFacultiesResponse) Reset() {
	*x = ListFacultiesResponse{}
	mi := &file_proto_faculty_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFacultiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFacultiesResponse) ProtoMessage() {}

func (x *ListFacultiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_faculty_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFacultiesResponse.ProtoReflect.Descriptor instead.
func (*ListFacultiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_faculty_proto_rawDescGZIP(), []int{8}
}

func (x *ListFacultiesResponse) GetFaculties() []*Faculty {
	if x != nil {
		return x.Faculties
	}
	return nil
}

var File_proto_faculty_proto protoreflect.FileDescriptor

const file_proto_faculty_proto_rawDesc = "" +
	"\n" +
	"\x13proto/faculty.proto\x12\afaculty\"\x85\x01\n" +
	"\aFaculty\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12 \n" +
	"\vdesignation\x18\x05 \x01(\tR\vdesignation\"\x82\x01\n" +
	"\x14CreateFacultyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1e\n" +
	"\n" +
	"department\x18\x03 \x01(\tR\n" +
	"department\x12 \n" +
	"\vdesignation\x18\x04 \x01(\tR\vdesignation\"#\n" +
	"\x11GetFacultyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x92\x01\n" +
	"\x14UpdateFacultyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1e\n" +
	"\n" +
	"department\x18\x04 \x01(\tR\n" +
	"department\x12 \n" +
	"\vdesignation\x18\x05 \x01(\tR\vdesignation\"&\n" +
	"\x14DeleteFacultyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"1\n" +
	"\x15DeleteFacultyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"=\n" +
	"\x0fFacultyResponse\x12*\n" +
	"\afaculty\x18\x01 \x01(\v2\x10.faculty.FacultyR\afaculty\"\x16\n" +
	"\x14ListFacultiesRequest\"G\n" +
	"\x15ListFacultiesResponse\x12.\n" +
	"\tfaculties\x18\x01 \x03(\v2\x10.faculty.FacultyR\tfaculties2\x88\x03\n" +
	"\x0eFacultyService\x12H\n" +
	"\rCreateFaculty\x12\x1d.faculty.CreateFacultyRequest\x1a\x18.faculty.FacultyResponse\x12B\n" +
	"\n" +
	"GetFaculty\x12\x1a.faculty.GetFacultyRequest\x1a\x18.faculty.FacultyResponse\x12H\n" +
	"\rUpdateFaculty\x12\x1d.faculty.UpdateFacultyRequest\x1a\x18.faculty.FacultyResponse\x12N\n" +
	"\rDeleteFaculty\x12\x1d.faculty.DeleteFacultyRequest\x1a\x1e.faculty.DeleteFacultyResponse\x12N\n" +
	"\rListFaculties\x12\x1d.faculty.ListFacultiesRequest\x1a\x1e.faculty.ListFacultiesResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_faculty_proto_rawDescOnce sync.Once
	file_proto_faculty_proto_rawDescData []byte
)

func file_proto_faculty_proto_rawDescGZIP() []byte {
	file_proto_faculty_proto_rawDescOnce.Do(func() {
		file_proto_faculty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_faculty_proto_rawDesc), len(file_proto_faculty_proto_rawDesc)))
	})
	return file_proto_faculty_proto_rawDescData
}

var file_proto_faculty_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_faculty_proto_goTypes = []any{
	(*Faculty)(nil),               // 0: faculty.Faculty
	(*CreateFacultyRequest)(nil),  // 1: faculty.CreateFacultyRequest
	(*GetFacultyRequest)(nil),     // 2: faculty.GetFacultyRequest
	(*UpdateFacultyRequest)(nil),  // 3: faculty.UpdateFacultyRequest
	(*DeleteFacultyRequest)(nil),  // 4: faculty.DeleteFacultyRequest
	(*DeleteFacultyResponse)(nil), // 5: faculty.DeleteFacultyResponse
	(*FacultyResponse)(nil),       // 6: faculty.FacultyResponse
	(*ListFacultiesRequest)(nil),  // 7: faculty.ListFacultiesRequest
	(*ListFacultiesResponse)(nil), // 8: faculty.ListFacultiesResponse
}
var file_proto_faculty_proto_depIdxs = []int32{
	0, // 0: faculty.FacultyResponse.faculty:type_name -> faculty.Faculty
	0, // 1: faculty.ListFacultiesResponse.faculties:type_name -> faculty.Faculty
	1, // 2: faculty.FacultyService.CreateFaculty:input_type -> faculty.CreateFacultyRequest
	2, // 3: faculty.FacultyService.GetFaculty:input_type -> faculty.GetFacultyRequest
	3, // 4: faculty.FacultyService.UpdateFaculty:input_type -> faculty.UpdateFacultyRequest
	4, // 5: faculty.FacultyService.DeleteFaculty:input_type -> faculty.DeleteFacultyRequest
	7, // 6: faculty.FacultyService.ListFaculties:input_type -> faculty.ListFacultiesRequest
	6, // 7: faculty.FacultyService.CreateFaculty:output_type -> faculty.FacultyResponse
	6, // 8: faculty.FacultyService.GetFaculty:output_type -> faculty.FacultyResponse
	6, // 9: faculty.FacultyService.UpdateFaculty:output_type -> faculty.FacultyResponse
	5, // 10: faculty.FacultyService.DeleteFaculty:output_type -> faculty.DeleteFacultyResponse
	8, // 11: faculty.FacultyService.ListFaculties:output_type -> faculty.ListFacultiesResponse
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_faculty_proto_init() }
func file_proto_faculty_proto_init() {
	if File_proto_faculty_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_faculty_proto_rawDesc), len(file_proto_faculty_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_faculty_proto_goTypes,
		DependencyIndexes: file_proto_faculty_proto_depIdxs,
		MessageInfos:      file_proto_faculty_proto_msgTypes,
	}.Build()
	File_proto_faculty_proto = out.File
	file_proto_faculty_proto_goTypes = nil
	file_proto_faculty_proto_depIdxs = nil
}
