// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/exam.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Exam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exam) Reset() {
	*x = Exam{}
	mi := &file_proto_exam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exam) ProtoMessage() {}

func (x *Exam) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exam.ProtoReflect.Descriptor instead.
func (*Exam) Descriptor() ([]byte, []int) {
	return file_proto_exam_proto_rawDescGZIP(), []int{0}
}

func (x *Exam) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Exam) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Exam) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *Exam) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CreateExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExamRequest) Reset() {
	*x = CreateExamRequest{}
	mi := &file_proto_exam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExamRequest) ProtoMessage() {}

func (x *CreateExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExamRequest.ProtoReflect.Descriptor instead.
func (*CreateExamRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_proto_rawDescGZIP(), []int{1}
}

func (x *CreateExamRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *CreateExamRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *CreateExamRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetExamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExamRequest) Reset() {
	*x = GetExamRequest{}
	mi := &file_proto_exam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExamRequest) ProtoMessage() {}

func (x *GetExamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExamRequest.ProtoReflect.Descriptor instead.
func (*GetExamRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_proto_rawDescGZIP(), []int{2}
}

func (x *GetExamRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ExamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exam          *Exam                  `protobuf:"bytes,1,opt,name=exam,proto3" json:"exam,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExamResponse) Reset() {
	*x = ExamResponse{}
	mi := &file_proto_exam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExamResponse) ProtoMessage() {}

func (x *ExamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExamResponse.ProtoReflect.Descriptor instead.
func (*ExamResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_proto_rawDescGZIP(), []int{3}
}

func (x *ExamResponse) GetExam() *Exam {
	if x != nil {
		return x.Exam
	}
	return nil
}

type ListExamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExamsRequest) Reset() {
	*x = ListExamsRequest{}
	mi := &file_proto_exam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExamsRequest) ProtoMessage() {}

func (x *ListExamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExamsRequest.ProtoReflect.Descriptor instead.
func (*ListExamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_exam_proto_rawDescGZIP(), []int{4}
}

type ListExamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exams         []*Exam                `protobuf:"bytes,1,rep,name=exams,proto3" json:"exams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListExamsResponse) Reset() {
	*x = ListExamsResponse{}
	mi := &file_proto_exam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListExamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListExamsResponse) ProtoMessage() {}

func (x *ListExamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_exam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListExamsResponse.ProtoReflect.Descriptor instead.
func (*ListExamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_exam_proto_rawDescGZIP(), []int{5}
}

func (x *ListExamsResponse) GetExams() []*Exam {
	if x != nil {
		return x.Exams
	}
	return nil
}

var File_proto_exam_proto protoreflect.FileDescriptor

const file_proto_exam_proto_rawDesc = "" +
	"\n" +
	"\x10proto/exam.proto\x12\x04exam\"X\n" +
	"\x04Exam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"U\n" +
	"\x11CreateExamRequest\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\" \n" +
	"\x0eGetExamRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\".\n" +
	"\fExamResponse\x12\x1e\n" +
	"\x04exam\x18\x01 \x01(\v2\n" +
	".exam.ExamR\x04exam\"\x12\n" +
	"\x10ListExamsRequest\"5\n" +
	"\x11ListExamsResponse\x12 \n" +
	"\x05exams\x18\x01 \x03(\v2\n" +
	".exam.ExamR\x05exams2\xbb\x01\n" +
	"\vExamService\x129\n" +
	"\n" +
	"CreateExam\x12\x17.exam.CreateExamRequest\x1a\x12.exam.ExamResponse\x123\n" +
	"\aGetExam\x12\x14.exam.GetExamRequest\x1a\x12.exam.ExamResponse\x12<\n" +
	"\tListExams\x12\x16.exam.ListExamsRequest\x1a\x17.exam.ListExamsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_exam_proto_rawDescOnce sync.Once
	file_proto_exam_proto_rawDescData []byte
)

func file_proto_exam_proto_rawDescGZIP() []byte {
	file_proto_exam_proto_rawDescOnce.Do(func() {
		file_proto_exam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_exam_proto_rawDesc), len(file_proto_exam_proto_rawDesc)))
	})
	return file_proto_exam_proto_rawDescData
}

var file_proto_exam_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_exam_proto_goTypes = []any{
	(*Exam)(nil),              // 0: exam.Exam
	(*CreateExamRequest)(nil), // 1: exam.CreateExamRequest
	(*GetExamRequest)(nil),    // 2: exam.GetExamRequest
	(*ExamResponse)(nil),      // 3: exam.ExamResponse
	(*ListExamsRequest)(nil),  // 4: exam.ListExamsRequest
	(*ListExamsResponse)(nil), // 5: exam.ListExamsResponse
}
var file_proto_exam_proto_depIdxs = []int32{
	0, // 0: exam.ExamResponse.exam:type_name -> exam.Exam
	0, // 1: exam.ListExamsResponse.exams:type_name -> exam.Exam
	1, // 2: exam.ExamService.CreateExam:input_type -> exam.CreateExamRequest
	2, // 3: exam.ExamService.GetExam:input_type -> exam.GetExamRequest
	4, // 4: exam.ExamService.ListExams:input_type -> exam.ListExamsRequest
	3, // 5: exam.ExamService.CreateExam:output_type -> exam.ExamResponse
	3, // 6: exam.ExamService.GetExam:output_type -> exam.ExamResponse
	5, // 7: exam.ExamService.ListExams:output_type -> exam.ListExamsResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_exam_proto_init() }
func file_proto_exam_proto_init() {
	if File_proto_exam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_exam_proto_rawDesc), len(file_proto_exam_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_exam_proto_goTypes,
		DependencyIndexes: file_proto_exam_proto_depIdxs,
		MessageInfos:      file_proto_exam_proto_msgTypes,
	}.Build()
	File_proto_exam_proto = out.File
	file_proto_exam_proto_goTypes = nil
	file_proto_exam_proto_depIdxs = nil
}
